services:
  - type: web
    name: DebateLabClient
    env: static
    staticPublishPath: FrontEnd/dist
    buildCommand: cd FrontEnd && npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
